let productDB = [
    {
        id: 1,
        title: "Filt Monster Sandwich",
        price: 50,
        imageUrl: "imgs/Eg-Filt-Mnstr-sndw.webp",
        description: "Lorem ipsum dolor sit amet.",
        qnty: 1,
        isMe: "N",
    },
    {
        id: 2,
        title: "Suber Dinner Combo",
        price: 120,
        imageUrl: "imgs/SUPER-DINNER_.webp",
        description: "Lorem ipsum dolor sit amet.",
        qnty: 1,
        isMe: "N",
    },
    {
        id: 3,
        title: "Twister Charger Combo",
        price: 55,
        imageUrl: "imgs/TwisterCharger Combo.webp",
        description: "Lorem ipsum dolor sit amet.",
        qnty: 1,
        isMe: "N",
    },
    {
        id: 4,
        title: "Mighty Zinger Sandwich",
        price: 35,
        imageUrl: "imgs/Mighty Zinger Combo.jpg",
        description: "Lorem ipsum dolor sit amet.",
        qnty: 1,
        isMe: "N",
    },
    {
        id: 5,
        title: "Twister Charger Sandwich",
        price: 30,
        imageUrl: "imgs/KFC_W8_TwisterCharger.webp",
        description: "Lorem ipsum dolor sit amet.",
        qnty: 1,
        isMe: "N",
    },
    {
        id: 6,
        title: "ColeSlaw",
        price: 10,
        imageUrl: "imgs/COLESLAW-pwa-250220.png",
        description: "Lorem ipsum dolor sit amet.",
        qnty: 1,
        isMe: "N",
    },
    {
        id: 7,
        title: "Mighty Love",
        price: 135,
        imageUrl: "imgs/Mighty Love 2021.png",
        description: "Lorem ipsum dolor sit amet.",
        qnty: 1,
        isMe: "N",
    },
    {
        id: 8,
        title: "Shrimp Add on",
        price: 25,
        imageUrl: "imgs/Shrimp Add-on.png",
        description: "Lorem ipsum dolor sit amet.",
        qnty: 1,
        isMe: "N",
    },
    {
        id: 9,
        title: "SUPER DINNER Strips",
        price: 115,
        imageUrl: "imgs/SUPER DINNER Strips 400x400 pix.png",
        description: "Lorem ipsum dolor sit amet.",
        qnty: 1,
        isMe: "N",
    },
    {
        id: 10,
        title: "Twister With Add On",
        price: 65,
        imageUrl: "imgs/TWISTER.png",
        description: "Lorem ipsum dolor sit amet.",
        qnty: 1,
        isMe: "N",
    },
];
